all:
	g++ ./TestParser.cpp ../src/Parser.cpp -I../src -o TestParser.o
	g++ ./TestSymbolTable.cpp ../src/SymbolTable.cpp -I../src -o TestSymbolTable.o

TestParser.o:
	g++ ./TestParser.cpp ../src/Parser.cpp -I../src -o TestParser.o

TestSymbolTable.o:
	g++ ./TestSymbolTable.cpp ../src/SymbolTable.cpp -I../src -o TestSymbolTable.o
